In [1]:
import numpy as np

In [3]:
# Finding unique values
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [5]:
# Find first index positions of unique values
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)
print(unique_values)

[ 0  2  3  4  5  6  7 12 13 14]
[11 12 13 14 15 16 17 18 19 20]


In [9]:
# Frequency of occurance
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [13]:
# Working with 2D arrays
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
print(a_2d)
# Unique values
unique_values = np.unique(a_2d)
print(unique_values)
# Unique rows
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
# Combining all functions in one
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True
)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [20]:
# Transposing and reshaping the matrix
## Functions: arr.reshape(), arr.transpose(), arr.T
data = np.array([[1,2],[3,4],[5,6]])
print(data)
print(data.reshape(2,3)) # 2 rows and 3 columns
print(data.reshape(3,2)) # 3 ro# ws and 2 columns

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [28]:
arr = np.arange(6).reshape((2,3))
print('Array: ', arr)
print('Transposed Array :',arr.transpose())
print('Transposed Array :',arr.T)

Array:  [[0 1 2]
 [3 4 5]]
Transposed Array : [[0 3]
 [1 4]
 [2 5]]
Transposed Array : [[0 3]
 [1 4]
 [2 5]]


In [37]:
# Flipping / Reversing an array along an axis
# function: np.flip()
# 1D Array
arr = np.array([1,2,3,4,5,6,7,8])
reversed_arr = np.flip(arr)
print('Reversed array :', reversed_arr)

#2D Array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('2D Array :', arr_2d)
reversed_arr_2d = np.flip(arr_2d)
print('Reversed 2D Array :', reversed_arr_2d)
reversed_arr_2d_rows = np.flip(arr_2d, axis=0)
print('Reversed with rows :', reversed_arr_2d_rows)
reversed_arr_2d_columns = np.flip(arr_2d, axis=1)
print('Reversed with columns :', reversed_arr_2d_columns)
## Reversing only one row by specifying index position
arr_2d[1] = np.flip(arr_2d[1])
print('Only 2nd row is flipped :', arr_2d)
## Reversing only one column
arr_2d[:,1] = np.flip(arr_2d[:,1])
print('Only 2nd column is flipped :', arr_2d)

Reversed array : [8 7 6 5 4 3 2 1]
2D Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reversed 2D Array : [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Reversed with rows : [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversed with columns : [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Only 2nd row is flipped : [[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
Only 2nd column is flipped : [[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [47]:
# Reshaping and flattening multidimensional arrays
## Functions: .flatten(), .ravel()
## revel() is a reference to the parent array
## Any changes to the new array will affect the parent array as well
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Array :', x)
print('Flattened Array :', x.flatten())

# Changing value of a1
a1 = x.flatten()
a1[0] = 99
print('Array :', x)
print('Flattened and replaced value 99 :', a1)

# Using ravel
a2 = x.ravel()
a2[0] = 98
print('Array :', x)
print('Flattened and replaced value 98 :', a2)
print('Parent Array Change :', x)

Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened and replaced value 99 : [99  2  3  4  5  6  7  8  9 10 11 12]
Array : [[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattned and replaced value 98 : [98  2  3  4  5  6  7  8  9 10 11 12]
Parent Array Change : [[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
