##  NumPy
- NumPy library contains multi-dimensional array and matrix data if structures
- Package provides 'ndarray', a homogenous n-dimensional array object

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
print(a)
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


(1, 6)

### What is the difference betweeen python list and numpy array ?
- NumPy gives ability to create arrays and manipulate numerical data inside them.
- Python list can contain different data types with in a single list, all of the elements in a NumPy array should be homogenous.
- Mathematical operations on array will only be efficient if array is homogenous.
- Array consumes less memory

#### Array:
- Array is a central structure of NumPy library.
- Elements of an array are all of same type (dtype)
- Indexed by a tuple of non-negative integers, by boolean, by another array, or by integers
- 'rank' of the array is the number of dimensions.
- 'shape' of the array is a tupel of integers giving the size of the array along each dimension.

In [3]:
a = np.array([1,2,3,4,5,6])
print(a) # Inspecting an array
a2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a2)  # Print Matrix
print(a2[0]) # only first row

[1 2 3 4 5 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


- 'ndarray' is short hand for N-dimensional array
- "Vector" is an array with a single dimension (no difference between rows and columns)
- "Matrix" refers to an array with two dimensions
- "Tensor" refers to an array with 3-D or higher dimensional arrays.

#### Attributes of an array
- Array is usually a fixed-size container of items of the same type and size.
- The number of dimensions and items in an array is defined by its shape.
- The shape of an array is a tuple of non-negative integers that specify the size of each dimension.
  - 'axes' - are the dimensions of an array
- 'attributes' reflect information intrinsic to the array itself

In [4]:
a = np.array([[0.,0.,0.],[1.,1.,1.]])
print(a)
print(a.shape)
# In this: first axis has a length of '2' and the second axis has a length '3'.

[[0. 0. 0.]
 [1. 1. 1.]]
(2, 3)


In [5]:
# Create a basic array:
## np.array(), np.zeros(), np.ones(), np.empty(), np.arange(),np.linespace(), dtype
a = np.array([1,2,3])
print(a)
b = np.zeros(2)
print(b)
c = np.ones(2)
print(c)
d = np.empty(2)
print(d)
e = np.arange(4)
print(e)
# Create an array with first number, last number, step size
f = np.arange(2,9,2)
print(f)
# Create an array with values that are spaced linearly in a specified interval.
g = np.linspace(0,10, num = 5)
print(g)
# Specify data type - By default data type is a floating point (np,float64) we can explicitly specify dtypes.
h = np.ones(2, dtype=np.int64)
print(h)

[1 2 3]
[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1 1]


In [6]:
# Adding, removing and sorting elements
## Sorting
arr = np.array([2,1,5,3,7,4,6,8])
print(arr)
arr_sorted = np.sort(arr)
print(arr_sorted)
### Other sort methods
# - argsort (indirect sort along a specified axis)
# - lexsort (indirect stable sort on multiple keys)
# - searchsorted (will find elements in a sorted array)
# - partition (is a partial sort)

## Concatenate arrays
a = np.array([1,2,3,4])
print(a)
b = np.array([5,6,7,8])
print(b)
print(np.concatenate((a,b)))

## Concatenate arrays with axis
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
print(np.concatenate((x,y), axis=0))

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]
[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
# Finding shape and size of an array:
## ndarray.ndim, ndarray.size, ndarray.shape
arr = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],

                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]],

                        [[0 ,1 ,2, 3],
                          [4, 5, 6, 7]]])
print(arr.ndim) # number of dimensions of the array
print(arr.size) # Total number of elements in an array
print(arr.shape) # Shape of the array

3
24
(3, 2, 4)


In [8]:
# Reshape an array
## arr.reshape()
## Note: When reshaping number of elements should not change
a = np.arange(6)
print(a)
b = a.reshape(3,2) # reshaping an array with three rows and two columns
print(b)
c = np.reshape(a, newshape=(1,6), order='C')
# 'newshape' shape should be compatible with original shape
# Order is an optional parameter
# order = 'C' read/write the elemensts using C-like index order
# order = 'F' Fortran like index order
# order = 'A' Fortran like index (only if contiguous in memory)
print(c)


[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4 5]]
