In [1]:
import numpy as np

In [12]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# Slicing and indexing revisited
print(data[0,1])
print(data[1:3]) #1-3rd row
print(data[0:2,0]) #0-2 rows and o th column

2
[[3 4]
 [5 6]]
[1 3]


In [14]:
# Aggregate matrices
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [18]:
# Aggregation of all
data2 = np.array([[1,2],[5,3],[4,6]])
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [20]:
#Using ones
data = np.array([[1,2],[3,4]])
ones = np.array([[1,1],[1,1]])
data + ones

array([[2, 3],
       [4, 5]])

In [22]:
#adding one row of ones
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([[1,1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [27]:
# Using np.ones
data = np.array([[1,2],[3,4],[5,6]])
print(data)
ones = np.ones((1,3,2)) #(no. of repetitions, 3 rows, 2 columns)
print(ones)
print(data + ones)

[[1 2]
 [3 4]
 [5 6]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[2. 3.]
  [4. 5.]
  [6. 7.]]]


In [30]:
print(np.ones(3))
print(np.zeros(3))

[1. 1. 1.]
[0. 0. 0.]


In [35]:
# Generate random numbers
rng = np.random.default_rng(0)
rng.random((4,2))

array([[0.63696169, 0.26978671],
       [0.04097352, 0.01652764],
       [0.81327024, 0.91275558],
       [0.60663578, 0.72949656]])

In [37]:
# Generate random integers
rng.integers(5, size=(4,2))

array([[1, 4],
       [2, 0],
       [3, 3],
       [4, 0]], dtype=int64)