In [4]:
import numpy as np

In [7]:
# Functions: np.vstack(), np.hstack(), np.hsplit(), .view(), copy()
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

arr1 = a[3:8]
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]


In [11]:
# Stacking arrays vertically and horizontally
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(a1)
print(a2)
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [15]:
# hsplit
x = np.arange(1,25).reshape(2,12)
print(x)
## Split array into three equally shaped arrays
print(np.hsplit(x,3))
## Split array after third and fourth column
print(np.hsplit(x, (3,4)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [19]:
# Using view method: view creates a new array object that looks at the same data as the original array.
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b1 = a[0, :]
print(b1)
b1[0] = 99
print(b1)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# Using copy method: Makes a complete copy of the arrray
b2 = a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
