In [1]:
import numpy as np

In [9]:
data = np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [11]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
