In [1]:
import numpy as np

In [9]:
data = np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [11]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
# Using a condition to index an array
## for example >= 5
five_up = (a >= 5)
print(a[five_up])
## for example select elements divisible by 2:
divisible_by_2 = a[a%2 ==0]
print(divisible_by_2)
## Using operations
c = a[(a > 2) & (a < 11)]
print(c)
d = (a > 5) | (a == 5)
print(d)

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [17]:
# using np.nonzero
## Prints indices of elements that are for example less than 5.
b = np.nonzero(a < 5)
print(b)
### Interpretation: In this example, a tuple of arrays are returned (one for each dimension).
### First array : row indices where values are found
### Second array: column indices where values are found

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [18]:
# Generate a list of coordinates where the elements exist, you can zip the arrays.
list_of_coordinates = list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [19]:
print(a[b])

[1 2 3 4]


In [20]:
# If the element you are looking for doesn't agree
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))
