### Mathematical expression with Numpy

$MeanSquareError = \frac{1}{n} \Sigma_{i=1}^n(Y_{prediction_i} - Y_i)^2$
-  error = (1/n) * np.sum(np.square(predictions - labels))


In [3]:
import numpy as np

In [11]:
# Math Operations
a = np.array([20,30,40,50])
b = np.arange(4)
print(b)
c = a - b
print('Substrcation :', c)
print('Square of b:',b**2)
print('Sin of a multiplied by 10:', 10*np.sin(a))
print('less than 35 :', a<35)

[0 1 2 3]
Substrcation : [20 29 38 47]
Square of b: [0 1 4 9]
Sin of a multiplied by 10: [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
less than 35 : [ True  True False False]


In [15]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print('Element wise Product :', A * B)
print('Matrix Product:', A@B)
print('Matrix Product:', A.dot(B))

Element wise Product : [[2 0]
 [0 4]]
Matrix Product: [[5 4]
 [3 4]]
Matrix Product: [[5 4]
 [3 4]]


In [27]:
a = np.arange(10)**3
print(a)
print(a[1:5])
a[:6:2] = 1000
print('start to position 6 and set every 2nd element to 1000', a)
a[ : :-1]
print('Reversed',a)

[  0   1   8  27  64 125 216 343 512 729]
[ 1  8 27 64]
start to position 6 and set every 2nd element to 1000 [1000    1 1000   27 1000  125  216  343  512  729]
Reversed [1000    1 1000   27 1000  125  216  343  512  729]


In [49]:
rg = np.random.default_rng(1)
b = rg.random((5,4))
print(b)
print('3rd Row and 4th Column :', b[2,3])
print('2nd Column :',b[: ,1])
print('2nd and 3rd rows and all columns :',b[1:3, :])
print('last row', b[-1])

[[0.51182162 0.9504637  0.14415961 0.94864945]
 [0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789]
 [0.1340417  0.40311299 0.20345524 0.26231334]]
3rd Row and 4th Column : 0.5381433132192782
2nd Column : [0.9504637  0.42332645 0.02755911 0.7884287  0.40311299]
2nd and 3rd rows and all columns : [[0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]]
last row [0.1340417  0.40311299 0.20345524 0.26231334]


In [58]:
# Changing shape of an array
a = np.floor(10*rg.random((3,4)))
print('Array:', a)
print('shape :', a.shape)
print('Flattened array: ', a.ravel())
print('Reshaped array: ', a.reshape(6,2))
print('Transposed array:', a.T)

Array: [[3. 4. 6. 4.]
 [5. 8. 7. 3.]
 [4. 3. 1. 2.]]
shape : (3, 4)
Flattened array:  [3. 4. 6. 4. 5. 8. 7. 3. 4. 3. 1. 2.]
Reshaped array:  [[3. 4.]
 [6. 4.]
 [5. 8.]
 [7. 3.]
 [4. 3.]
 [1. 2.]]
Transposed array: [[3. 5. 4.]
 [4. 8. 3.]
 [6. 7. 1.]
 [4. 3. 2.]]
